services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    restart: always
    env_file:
      - .env.prod
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

  app:
    image: ${DOCKER_USERNAME}/sb-todo-nestjs-server
    container_name: nestjs_app
    restart: always
    env_file:
      - .env.prod
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    depends_on:
      - db
      - redis
    command: /bin/sh -c "npm run migration:run:prod && npm run start:prod"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  postgres_data:
