services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env.dev
    volumes:
      - ./volumes/dev/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - sb-dev

  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - .env.dev
    volumes:
      - ./volumes/dev/redis-data:/data
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    networks:
      - sb-dev

networks:
  sb-dev:
